services: 
  db:
    image: grafana/tns-db:latest
    command:
      - '-log.level=debug'
    ports:
      - 8000:80

  app:
    image: grafana/tns-app:latest
    command:
      - '-log.level=debug'
      - 'http://db'
    links:
      - db
    ports:
      - 8001:80

  loadgen:
    image: grafana/tns-loadgen:latest
    command:
      - '-log.level=debug'
      - 'http://app'
    links:
      - app
    ports:
      - 8002:80
